require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.colorscheme"
-- spec "user.devicons"
spec "user.miniicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.null-ls"
spec "user.illuminate"
spec "user.telescope"
spec "user.telescope-tabs"
-- spec "user.nvimtree"
spec "user.neotree"
spec "user.lualine"
spec "user.whichkey"
spec "user.dap"
-- spec "user.autotag"
-- spec "user.sleuth"
spec "user.cmp"
spec "user.autopairs"
spec "user.comment"
spec "user.gitsigns"
spec "user.neogit"
spec "user.diffview"
spec "user.indentline"
spec "user.alpha"
spec "user.netrw"
spec "user.project"
spec "user.toggleterm"
spec "user.bufdelete"
spec "user.luarocks"
-- spec "user.image"
-- Extras
spec "user.extras.notify"
spec "user.extras.colorizer"
-- spec "user.extras.smoothie"
spec "user.extras.neoscroll"
spec "user.extras.copilot"
spec "user.extras.modicator"
-- spec "user.extras.rainbow"
spec "user.extras.matchup"
spec "user.extras.bqf"
spec "user.extras.dial"
spec "user.extras.nui"
spec "user.extras.ufo"
spec "user.extras.dressing"
spec "user.extras.surround"
spec "user.extras.eyeliner"
spec "user.extras.numb"
spec "user.extras.jaq"
spec "user.extras.navbuddy"
-- spec "user.extras.minifiles"
spec "user.extras.oil"
-- spec "user.extras.noice"
spec "user.extras.fidget"
spec "user.extras.neotab"
spec "user.extras.neotest"
spec "user.extras.cmp-tabnine"
spec "user.extras.lab"
spec "user.extras.tabby"
spec "user.extras.various-textobjs"
spec "user.extras.spider"
-- spec "user.extras.test"
spec "user.extras.nostr"
spec "user.extras.typescript-tools"
spec "user.extras.tsc"
spec "user.extras.gitlinker"
spec "user.extras.fugitive"
spec "user.extras.harpoon"
-- spec "user.extras.trailblazer"
spec "user.extras.package-info"
spec "user.extras.todo-comments"
spec "user.extras.trouble"
spec "user.extras.cellular-automaton"
spec "user.extras.rustacean"
spec "user.extras.gopher"
spec "user.extras.crates"
spec "user.extras.gp"
-- spec "user.extras.dingllm"
require "user.lazy"
